//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_consol
{
    using System;
    using System.Collections.Generic;
    
    public partial class alireza_test
    {
        public int Id { get; set; }
    }
}
