//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_cus
    {
        public int rdf { get; set; }
        public int SysID { get; set; }
        public int Shmo { get; set; }
        public string user_ { get; set; }
    
        public virtual CUSTOMERS CUSTOMERS { get; set; }
    }
}
