//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TellBook
    {
        public int ID { get; set; }
        public string Moname { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Tell1 { get; set; }
        public string Tell2 { get; set; }
        public string Tell3 { get; set; }
        public string Tell4 { get; set; }
        public string Cell1 { get; set; }
        public string Cell2 { get; set; }
        public string Cell3 { get; set; }
        public bool Active { get; set; }
        public int LastEditedUser { get; set; }
        public int shmo { get; set; }
    }
}
