//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class visitors
    {
        public int vis_rdf { get; set; }
        public string vis_name { get; set; }
        public string vis_addre { get; set; }
        public string vis_tell1 { get; set; }
        public string vis_tell2 { get; set; }
        public string vis_cell { get; set; }
        public decimal vis_man { get; set; }
        public int VIs_region { get; set; }
        public string viss_date { get; set; }
        public string active { get; set; }
        public Nullable<int> vis_city { get; set; }
        public Nullable<decimal> h_sabet { get; set; }
        public byte[] image { get; set; }
        public string user { get; set; }
        public string is_supervisor { get; set; }
        public Nullable<int> supervisor_rdf { get; set; }
        public Nullable<decimal> supervisor_per { get; set; }
        public Nullable<decimal> dar_z { get; set; }
        public Nullable<decimal> eteb { get; set; }
        public Nullable<decimal> per_p_d_naghd { get; set; }
        public Nullable<decimal> per_p_d_check { get; set; }
        public Nullable<decimal> per_jar_bch { get; set; }
        public Nullable<int> kind { get; set; }
        public string user_ { get; set; }
        public Nullable<int> tedad_fmmt { get; set; }
        public Nullable<decimal> mab_fmmt { get; set; }
        public Nullable<int> rdf_device { get; set; }
        public int TedadFactorMojazMande { get; set; }
        public decimal MablaghMojazMandeJahatFactorha { get; set; }
        public Nullable<bool> Type1 { get; set; }
        public Nullable<bool> Type2 { get; set; }
    }
}
